---
- name: Restart nslcd
  service: name=nslcd state=restarted

- name: Validate SSH config
  command: sshd -t
  notify: Reload SSH daemon

- name: Reload SSH daemon
  service: name=sshd state=reloaded
